namespace Wireframe
{
    /// This file is auto-generated by the Build Uploader package.
    /// Do not modify this file directly as changes will be lost when it is regenerated.
    public static class BuildUploader_AutoGeneratedMenuItems
    {
    }
}
