// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameData {

  /// <summary>Holder for reflection information generated from GameData.proto</summary>
  public static partial class GameDataReflection {

    #region Descriptor
    /// <summary>File descriptor for GameData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5HYW1lRGF0YS5wcm90bxIIR2FtZURhdGEi3gIKBERhdGESJAoITG9iYnlD",
            "TUQYASABKA4yEi5HYW1lRGF0YS5Mb2JieUNNRBIiCgdHYW1lQ01EGAIgASgO",
            "MhEuR2FtZURhdGEuR2FtZUNNRBIiCgdSb29tQ01EGAMgASgOMhEuR2FtZURh",
            "dGEuUm9vbUNNRBIyCg9NZXNzYWdlUHJvdG9jb2wYBCABKA4yGS5HYW1lRGF0",
            "YS5NZXNzYWdlUHJvdG9jb2wSKgoLTWVzc2FnZVR5cGUYBSABKA4yFS5HYW1l",
            "RGF0YS5NZXNzYWdlVHlwZRIyCg9NZXNzYWdlU2VuZFR5cGUYBiABKA4yGS5H",
            "YW1lRGF0YS5NZXNzYWdlU2VuZFR5cGUSLgoNVHJhbnNmcm9tRGF0YRgHIAEo",
            "CzIXLkdhbWVEYXRhLlRyYW5zZnJvbURhdGESJAoIUm9vbURhdGEYCCABKAsy",
            "Ei5HYW1lRGF0YS5Sb29tRGF0YSIqCgdWZWN0b3IzEgkKAVgYASABKAISCQoB",
            "WRgCIAEoAhIJCgFaGAMgASgCIhoKCFJvb21EYXRhEg4KBlJvb21JZBgBIAEo",
            "BSLUAQoNVHJhbnNmcm9tRGF0YRIoCg1Mb2NhbFBvc2l0aW9uGAEgASgLMhEu",
            "R2FtZURhdGEuVmVjdG9yMxIjCghQb3NpdGlvbhgCIAEoCzIRLkdhbWVEYXRh",
            "LlZlY3RvcjMSKAoNTG9jYWxSb3RhdGlvbhgDIAEoCzIRLkdhbWVEYXRhLlZl",
            "Y3RvcjMSIwoIUm90YXRpb24YBCABKAsyES5HYW1lRGF0YS5WZWN0b3IzEiUK",
            "CkxvY2FsU2NhbGUYBSABKAsyES5HYW1lRGF0YS5WZWN0b3IzIhcKCEVycm9y",
            "TXNnEgsKA01zZxgBIAEoCSpICghMb2JieUNNRBIMCghNYXRjUm9vbRAAEgsK",
            "B0pvaW5Sb20QARITCg9NYXRjaHN1Y2Nlc3NmdWwQAhIMCghFcnJMb2JieRAD",
            "KhYKB0dhbWVDTUQSCwoHRXJyR2FtZRAAKk4KB1Jvb21DTUQSCAoESm9pbhAA",
            "EggKBFF1aXQQARIJCgVSZWFkeRACEgsKB05vUmVhZHkQAxIMCghBbGxSZWFk",
            "eRAEEgkKBVN0YXJ0EAUqIwoPTWVzc2FnZVByb3RvY29sEgcKA1RjcBAAEgcK",
            "A1VkcBABKiwKC01lc3NhZ2VUeXBlEggKBFJvb20QABIJCgVMb2JieRABEggK",
            "BEdhbWUQAiovCg9NZXNzYWdlU2VuZFR5cGUSBwoDQWxsEAASCAoEU2VsZhAB",
            "EgkKBU90aGVyEAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameData.LobbyCMD), typeof(global::GameData.GameCMD), typeof(global::GameData.RoomCMD), typeof(global::GameData.MessageProtocol), typeof(global::GameData.MessageType), typeof(global::GameData.MessageSendType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GameData.Data), global::GameData.Data.Parser, new[]{ "LobbyCMD", "GameCMD", "RoomCMD", "MessageProtocol", "MessageType", "MessageSendType", "TransfromData", "RoomData" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameData.Vector3), global::GameData.Vector3.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameData.RoomData), global::GameData.RoomData.Parser, new[]{ "RoomId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameData.TransfromData), global::GameData.TransfromData.Parser, new[]{ "LocalPosition", "Position", "LocalRotation", "Rotation", "LocalScale" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameData.ErrorMsg), global::GameData.ErrorMsg.Parser, new[]{ "Msg" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum LobbyCMD {
    [pbr::OriginalName("MatcRoom")] MatcRoom = 0,
    [pbr::OriginalName("JoinRom")] JoinRom = 1,
    [pbr::OriginalName("Matchsuccessful")] Matchsuccessful = 2,
    [pbr::OriginalName("ErrLobby")] ErrLobby = 3,
  }

  public enum GameCMD {
    [pbr::OriginalName("ErrGame")] ErrGame = 0,
  }

  public enum RoomCMD {
    [pbr::OriginalName("Join")] Join = 0,
    [pbr::OriginalName("Quit")] Quit = 1,
    [pbr::OriginalName("Ready")] Ready = 2,
    [pbr::OriginalName("NoReady")] NoReady = 3,
    [pbr::OriginalName("AllReady")] AllReady = 4,
    [pbr::OriginalName("Start")] Start = 5,
  }

  public enum MessageProtocol {
    [pbr::OriginalName("Tcp")] Tcp = 0,
    [pbr::OriginalName("Udp")] Udp = 1,
  }

  public enum MessageType {
    [pbr::OriginalName("Room")] Room = 0,
    [pbr::OriginalName("Lobby")] Lobby = 1,
    [pbr::OriginalName("Game")] Game = 2,
  }

  public enum MessageSendType {
    [pbr::OriginalName("All")] All = 0,
    [pbr::OriginalName("Self")] Self = 1,
    [pbr::OriginalName("Other")] Other = 2,
  }

  #endregion

  #region Messages
  public sealed partial class Data : pb::IMessage<Data>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Data> _parser = new pb::MessageParser<Data>(() => new Data());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Data> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameData.GameDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Data() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Data(Data other) : this() {
      lobbyCMD_ = other.lobbyCMD_;
      gameCMD_ = other.gameCMD_;
      roomCMD_ = other.roomCMD_;
      messageProtocol_ = other.messageProtocol_;
      messageType_ = other.messageType_;
      messageSendType_ = other.messageSendType_;
      transfromData_ = other.transfromData_ != null ? other.transfromData_.Clone() : null;
      roomData_ = other.roomData_ != null ? other.roomData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Data Clone() {
      return new Data(this);
    }

    /// <summary>Field number for the "LobbyCMD" field.</summary>
    public const int LobbyCMDFieldNumber = 1;
    private global::GameData.LobbyCMD lobbyCMD_ = global::GameData.LobbyCMD.MatcRoom;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameData.LobbyCMD LobbyCMD {
      get { return lobbyCMD_; }
      set {
        lobbyCMD_ = value;
      }
    }

    /// <summary>Field number for the "GameCMD" field.</summary>
    public const int GameCMDFieldNumber = 2;
    private global::GameData.GameCMD gameCMD_ = global::GameData.GameCMD.ErrGame;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameData.GameCMD GameCMD {
      get { return gameCMD_; }
      set {
        gameCMD_ = value;
      }
    }

    /// <summary>Field number for the "RoomCMD" field.</summary>
    public const int RoomCMDFieldNumber = 3;
    private global::GameData.RoomCMD roomCMD_ = global::GameData.RoomCMD.Join;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameData.RoomCMD RoomCMD {
      get { return roomCMD_; }
      set {
        roomCMD_ = value;
      }
    }

    /// <summary>Field number for the "MessageProtocol" field.</summary>
    public const int MessageProtocolFieldNumber = 4;
    private global::GameData.MessageProtocol messageProtocol_ = global::GameData.MessageProtocol.Tcp;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameData.MessageProtocol MessageProtocol {
      get { return messageProtocol_; }
      set {
        messageProtocol_ = value;
      }
    }

    /// <summary>Field number for the "MessageType" field.</summary>
    public const int MessageTypeFieldNumber = 5;
    private global::GameData.MessageType messageType_ = global::GameData.MessageType.Room;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameData.MessageType MessageType {
      get { return messageType_; }
      set {
        messageType_ = value;
      }
    }

    /// <summary>Field number for the "MessageSendType" field.</summary>
    public const int MessageSendTypeFieldNumber = 6;
    private global::GameData.MessageSendType messageSendType_ = global::GameData.MessageSendType.All;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameData.MessageSendType MessageSendType {
      get { return messageSendType_; }
      set {
        messageSendType_ = value;
      }
    }

    /// <summary>Field number for the "TransfromData" field.</summary>
    public const int TransfromDataFieldNumber = 7;
    private global::GameData.TransfromData transfromData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameData.TransfromData TransfromData {
      get { return transfromData_; }
      set {
        transfromData_ = value;
      }
    }

    /// <summary>Field number for the "RoomData" field.</summary>
    public const int RoomDataFieldNumber = 8;
    private global::GameData.RoomData roomData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameData.RoomData RoomData {
      get { return roomData_; }
      set {
        roomData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Data other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LobbyCMD != other.LobbyCMD) return false;
      if (GameCMD != other.GameCMD) return false;
      if (RoomCMD != other.RoomCMD) return false;
      if (MessageProtocol != other.MessageProtocol) return false;
      if (MessageType != other.MessageType) return false;
      if (MessageSendType != other.MessageSendType) return false;
      if (!object.Equals(TransfromData, other.TransfromData)) return false;
      if (!object.Equals(RoomData, other.RoomData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LobbyCMD != global::GameData.LobbyCMD.MatcRoom) hash ^= LobbyCMD.GetHashCode();
      if (GameCMD != global::GameData.GameCMD.ErrGame) hash ^= GameCMD.GetHashCode();
      if (RoomCMD != global::GameData.RoomCMD.Join) hash ^= RoomCMD.GetHashCode();
      if (MessageProtocol != global::GameData.MessageProtocol.Tcp) hash ^= MessageProtocol.GetHashCode();
      if (MessageType != global::GameData.MessageType.Room) hash ^= MessageType.GetHashCode();
      if (MessageSendType != global::GameData.MessageSendType.All) hash ^= MessageSendType.GetHashCode();
      if (transfromData_ != null) hash ^= TransfromData.GetHashCode();
      if (roomData_ != null) hash ^= RoomData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LobbyCMD != global::GameData.LobbyCMD.MatcRoom) {
        output.WriteRawTag(8);
        output.WriteEnum((int) LobbyCMD);
      }
      if (GameCMD != global::GameData.GameCMD.ErrGame) {
        output.WriteRawTag(16);
        output.WriteEnum((int) GameCMD);
      }
      if (RoomCMD != global::GameData.RoomCMD.Join) {
        output.WriteRawTag(24);
        output.WriteEnum((int) RoomCMD);
      }
      if (MessageProtocol != global::GameData.MessageProtocol.Tcp) {
        output.WriteRawTag(32);
        output.WriteEnum((int) MessageProtocol);
      }
      if (MessageType != global::GameData.MessageType.Room) {
        output.WriteRawTag(40);
        output.WriteEnum((int) MessageType);
      }
      if (MessageSendType != global::GameData.MessageSendType.All) {
        output.WriteRawTag(48);
        output.WriteEnum((int) MessageSendType);
      }
      if (transfromData_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(TransfromData);
      }
      if (roomData_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(RoomData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LobbyCMD != global::GameData.LobbyCMD.MatcRoom) {
        output.WriteRawTag(8);
        output.WriteEnum((int) LobbyCMD);
      }
      if (GameCMD != global::GameData.GameCMD.ErrGame) {
        output.WriteRawTag(16);
        output.WriteEnum((int) GameCMD);
      }
      if (RoomCMD != global::GameData.RoomCMD.Join) {
        output.WriteRawTag(24);
        output.WriteEnum((int) RoomCMD);
      }
      if (MessageProtocol != global::GameData.MessageProtocol.Tcp) {
        output.WriteRawTag(32);
        output.WriteEnum((int) MessageProtocol);
      }
      if (MessageType != global::GameData.MessageType.Room) {
        output.WriteRawTag(40);
        output.WriteEnum((int) MessageType);
      }
      if (MessageSendType != global::GameData.MessageSendType.All) {
        output.WriteRawTag(48);
        output.WriteEnum((int) MessageSendType);
      }
      if (transfromData_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(TransfromData);
      }
      if (roomData_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(RoomData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LobbyCMD != global::GameData.LobbyCMD.MatcRoom) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) LobbyCMD);
      }
      if (GameCMD != global::GameData.GameCMD.ErrGame) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) GameCMD);
      }
      if (RoomCMD != global::GameData.RoomCMD.Join) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RoomCMD);
      }
      if (MessageProtocol != global::GameData.MessageProtocol.Tcp) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MessageProtocol);
      }
      if (MessageType != global::GameData.MessageType.Room) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MessageType);
      }
      if (MessageSendType != global::GameData.MessageSendType.All) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MessageSendType);
      }
      if (transfromData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TransfromData);
      }
      if (roomData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RoomData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Data other) {
      if (other == null) {
        return;
      }
      if (other.LobbyCMD != global::GameData.LobbyCMD.MatcRoom) {
        LobbyCMD = other.LobbyCMD;
      }
      if (other.GameCMD != global::GameData.GameCMD.ErrGame) {
        GameCMD = other.GameCMD;
      }
      if (other.RoomCMD != global::GameData.RoomCMD.Join) {
        RoomCMD = other.RoomCMD;
      }
      if (other.MessageProtocol != global::GameData.MessageProtocol.Tcp) {
        MessageProtocol = other.MessageProtocol;
      }
      if (other.MessageType != global::GameData.MessageType.Room) {
        MessageType = other.MessageType;
      }
      if (other.MessageSendType != global::GameData.MessageSendType.All) {
        MessageSendType = other.MessageSendType;
      }
      if (other.transfromData_ != null) {
        if (transfromData_ == null) {
          TransfromData = new global::GameData.TransfromData();
        }
        TransfromData.MergeFrom(other.TransfromData);
      }
      if (other.roomData_ != null) {
        if (roomData_ == null) {
          RoomData = new global::GameData.RoomData();
        }
        RoomData.MergeFrom(other.RoomData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LobbyCMD = (global::GameData.LobbyCMD) input.ReadEnum();
            break;
          }
          case 16: {
            GameCMD = (global::GameData.GameCMD) input.ReadEnum();
            break;
          }
          case 24: {
            RoomCMD = (global::GameData.RoomCMD) input.ReadEnum();
            break;
          }
          case 32: {
            MessageProtocol = (global::GameData.MessageProtocol) input.ReadEnum();
            break;
          }
          case 40: {
            MessageType = (global::GameData.MessageType) input.ReadEnum();
            break;
          }
          case 48: {
            MessageSendType = (global::GameData.MessageSendType) input.ReadEnum();
            break;
          }
          case 58: {
            if (transfromData_ == null) {
              TransfromData = new global::GameData.TransfromData();
            }
            input.ReadMessage(TransfromData);
            break;
          }
          case 66: {
            if (roomData_ == null) {
              RoomData = new global::GameData.RoomData();
            }
            input.ReadMessage(RoomData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LobbyCMD = (global::GameData.LobbyCMD) input.ReadEnum();
            break;
          }
          case 16: {
            GameCMD = (global::GameData.GameCMD) input.ReadEnum();
            break;
          }
          case 24: {
            RoomCMD = (global::GameData.RoomCMD) input.ReadEnum();
            break;
          }
          case 32: {
            MessageProtocol = (global::GameData.MessageProtocol) input.ReadEnum();
            break;
          }
          case 40: {
            MessageType = (global::GameData.MessageType) input.ReadEnum();
            break;
          }
          case 48: {
            MessageSendType = (global::GameData.MessageSendType) input.ReadEnum();
            break;
          }
          case 58: {
            if (transfromData_ == null) {
              TransfromData = new global::GameData.TransfromData();
            }
            input.ReadMessage(TransfromData);
            break;
          }
          case 66: {
            if (roomData_ == null) {
              RoomData = new global::GameData.RoomData();
            }
            input.ReadMessage(RoomData);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Vector3 : pb::IMessage<Vector3>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Vector3> _parser = new pb::MessageParser<Vector3>(() => new Vector3());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Vector3> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameData.GameDataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Vector3() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Vector3(Vector3 other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Vector3 Clone() {
      return new Vector3(this);
    }

    /// <summary>Field number for the "X" field.</summary>
    public const int XFieldNumber = 1;
    private float x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "Y" field.</summary>
    public const int YFieldNumber = 2;
    private float y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "Z" field.</summary>
    public const int ZFieldNumber = 3;
    private float z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Vector3);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Vector3 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (X != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (X != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (X != 0F) {
        size += 1 + 4;
      }
      if (Y != 0F) {
        size += 1 + 4;
      }
      if (Z != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Vector3 other) {
      if (other == null) {
        return;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
      if (other.Z != 0F) {
        Z = other.Z;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RoomData : pb::IMessage<RoomData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RoomData> _parser = new pb::MessageParser<RoomData>(() => new RoomData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RoomData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameData.GameDataReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomData(RoomData other) : this() {
      roomId_ = other.roomId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomData Clone() {
      return new RoomData(this);
    }

    /// <summary>Field number for the "RoomId" field.</summary>
    public const int RoomIdFieldNumber = 1;
    private int roomId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoomId {
      get { return roomId_; }
      set {
        roomId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RoomData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RoomData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RoomId != other.RoomId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RoomId != 0) hash ^= RoomId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RoomId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RoomId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RoomId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RoomId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RoomId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoomId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RoomData other) {
      if (other == null) {
        return;
      }
      if (other.RoomId != 0) {
        RoomId = other.RoomId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RoomId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RoomId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TransfromData : pb::IMessage<TransfromData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TransfromData> _parser = new pb::MessageParser<TransfromData>(() => new TransfromData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TransfromData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameData.GameDataReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransfromData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransfromData(TransfromData other) : this() {
      localPosition_ = other.localPosition_ != null ? other.localPosition_.Clone() : null;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      localRotation_ = other.localRotation_ != null ? other.localRotation_.Clone() : null;
      rotation_ = other.rotation_ != null ? other.rotation_.Clone() : null;
      localScale_ = other.localScale_ != null ? other.localScale_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransfromData Clone() {
      return new TransfromData(this);
    }

    /// <summary>Field number for the "LocalPosition" field.</summary>
    public const int LocalPositionFieldNumber = 1;
    private global::GameData.Vector3 localPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameData.Vector3 LocalPosition {
      get { return localPosition_; }
      set {
        localPosition_ = value;
      }
    }

    /// <summary>Field number for the "Position" field.</summary>
    public const int PositionFieldNumber = 2;
    private global::GameData.Vector3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameData.Vector3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "LocalRotation" field.</summary>
    public const int LocalRotationFieldNumber = 3;
    private global::GameData.Vector3 localRotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameData.Vector3 LocalRotation {
      get { return localRotation_; }
      set {
        localRotation_ = value;
      }
    }

    /// <summary>Field number for the "Rotation" field.</summary>
    public const int RotationFieldNumber = 4;
    private global::GameData.Vector3 rotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameData.Vector3 Rotation {
      get { return rotation_; }
      set {
        rotation_ = value;
      }
    }

    /// <summary>Field number for the "LocalScale" field.</summary>
    public const int LocalScaleFieldNumber = 5;
    private global::GameData.Vector3 localScale_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameData.Vector3 LocalScale {
      get { return localScale_; }
      set {
        localScale_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TransfromData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TransfromData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(LocalPosition, other.LocalPosition)) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (!object.Equals(LocalRotation, other.LocalRotation)) return false;
      if (!object.Equals(Rotation, other.Rotation)) return false;
      if (!object.Equals(LocalScale, other.LocalScale)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (localPosition_ != null) hash ^= LocalPosition.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (localRotation_ != null) hash ^= LocalRotation.GetHashCode();
      if (rotation_ != null) hash ^= Rotation.GetHashCode();
      if (localScale_ != null) hash ^= LocalScale.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (localPosition_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(LocalPosition);
      }
      if (position_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Position);
      }
      if (localRotation_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(LocalRotation);
      }
      if (rotation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Rotation);
      }
      if (localScale_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LocalScale);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (localPosition_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(LocalPosition);
      }
      if (position_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Position);
      }
      if (localRotation_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(LocalRotation);
      }
      if (rotation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Rotation);
      }
      if (localScale_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LocalScale);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (localPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LocalPosition);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (localRotation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LocalRotation);
      }
      if (rotation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rotation);
      }
      if (localScale_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LocalScale);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TransfromData other) {
      if (other == null) {
        return;
      }
      if (other.localPosition_ != null) {
        if (localPosition_ == null) {
          LocalPosition = new global::GameData.Vector3();
        }
        LocalPosition.MergeFrom(other.LocalPosition);
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::GameData.Vector3();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.localRotation_ != null) {
        if (localRotation_ == null) {
          LocalRotation = new global::GameData.Vector3();
        }
        LocalRotation.MergeFrom(other.LocalRotation);
      }
      if (other.rotation_ != null) {
        if (rotation_ == null) {
          Rotation = new global::GameData.Vector3();
        }
        Rotation.MergeFrom(other.Rotation);
      }
      if (other.localScale_ != null) {
        if (localScale_ == null) {
          LocalScale = new global::GameData.Vector3();
        }
        LocalScale.MergeFrom(other.LocalScale);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (localPosition_ == null) {
              LocalPosition = new global::GameData.Vector3();
            }
            input.ReadMessage(LocalPosition);
            break;
          }
          case 18: {
            if (position_ == null) {
              Position = new global::GameData.Vector3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 26: {
            if (localRotation_ == null) {
              LocalRotation = new global::GameData.Vector3();
            }
            input.ReadMessage(LocalRotation);
            break;
          }
          case 34: {
            if (rotation_ == null) {
              Rotation = new global::GameData.Vector3();
            }
            input.ReadMessage(Rotation);
            break;
          }
          case 42: {
            if (localScale_ == null) {
              LocalScale = new global::GameData.Vector3();
            }
            input.ReadMessage(LocalScale);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (localPosition_ == null) {
              LocalPosition = new global::GameData.Vector3();
            }
            input.ReadMessage(LocalPosition);
            break;
          }
          case 18: {
            if (position_ == null) {
              Position = new global::GameData.Vector3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 26: {
            if (localRotation_ == null) {
              LocalRotation = new global::GameData.Vector3();
            }
            input.ReadMessage(LocalRotation);
            break;
          }
          case 34: {
            if (rotation_ == null) {
              Rotation = new global::GameData.Vector3();
            }
            input.ReadMessage(Rotation);
            break;
          }
          case 42: {
            if (localScale_ == null) {
              LocalScale = new global::GameData.Vector3();
            }
            input.ReadMessage(LocalScale);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ErrorMsg : pb::IMessage<ErrorMsg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ErrorMsg> _parser = new pb::MessageParser<ErrorMsg>(() => new ErrorMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ErrorMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameData.GameDataReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ErrorMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ErrorMsg(ErrorMsg other) : this() {
      msg_ = other.msg_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ErrorMsg Clone() {
      return new ErrorMsg(this);
    }

    /// <summary>Field number for the "Msg" field.</summary>
    public const int MsgFieldNumber = 1;
    private string msg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Msg {
      get { return msg_; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ErrorMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ErrorMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Msg != other.Msg) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Msg.Length != 0) hash ^= Msg.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Msg.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Msg.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Msg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ErrorMsg other) {
      if (other == null) {
        return;
      }
      if (other.Msg.Length != 0) {
        Msg = other.Msg;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Msg = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Msg = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
