namespace Wireframe
{
    /// This file is auto-generated by the Build Uploader package.
    /// Do not modify this file directly as changes will be lost when it is regenerated.
    public static class BuildUploader_AutoGeneratedMenuItems
    {
        [UnityEditor.MenuItem("Window/Build Uploader/Quick Upload/1. Default", false, 1000)]
        public static void BuildUploader_QuickUpload_8e2104()
        {
            AutoGenerateMenuItems.BeginUploadingProfile("8e2104", "Default");
        }
    }
}
